stages:
  preprocess_train:
    cmd: python3 src/preprocess.py "data/HistoricDump.tsv"
    deps:
      - src/preprocess.py
      - data/HistoricDump.tsv
    outs:
      - data/preprocessed_HistoricDump.tsv

  preprocess_test:
    cmd: python3 src/preprocess.py "data/FreshDump.tsv"
    deps:
      - src/preprocess.py
      - data/FreshDump.tsv
    outs:
      - data/preprocessed_FreshDump.tsv

  train:
    cmd: python3 src/train.py "data/preprocessed_HistoricDump.tsv"
    deps:
      - src/train.py
      - data/preprocessed_HistoricDump.tsv
    outs:
      - output/bow.pkl
      - output/model
    metrics:
      - output/performance.json:
          cache: true

  test:
    cmd: python3 src/test.py "data/preprocessed_FreshDump.tsv"
    deps:
      - src/test.py
      - data/preprocessed_FreshDump.tsv
      - output/bow.pkl
      - output/model
