name: Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pytest Suite
        run: pytest --junitxml=junit/test-results.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

      - name: Run pylint
        run: pylint ./src --output-format=text:pylint-report.txt

      - name: Upload pylint report
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: pylint-report.txt

      - name: Run dslint
        run: pylint --load-plugins=dslinter ./src --output-format=text:dslinter-report.txt,colorized

      - name: Upload dslinter report
        uses: actions/upload-artifact@v3
        with:
          name: dslinter-report
          path: dslinter-report.txt

      - name: Run mllint
        run: mllint -o mllint-report.md

      - name: Upload mllint report
        uses: actions/upload-artifact@v3
        with:
          name: mllint-report
          path: mllint-report.md